New version of bftools (Version: 5.1.0-DEV  VCS revision: c558413 Build date: 14 March 2014)

diff --git a/bftools/ijview b/bftools/ijview
--- a/bftools/ijview
+++ b/bftools/ijview
@@ -3,33 +3,43 @@
 # ijview: a script for displaying an image file in ImageJ
 #         using the Bio-Formats Importer plugin
 
-# Required JARs: loci_tools.jar, ij.jar
+# Required JARs: loci_tools.jar or bioformats_package.jar, ij.jar
 
-# JAR libraries must be in the same directory as this
-# command line script for the command to function.
+BF_DIR=`dirname "$0"`
 
-# If you are a developer working from source and have
-# the LOCI classes in your CLASSPATH, you can set the
-# LOCI_DEVEL environment variable to use them instead.
+source "$BF_DIR/config.sh"
 
-PROG=loci.plugins.in.Importer
-DIR=`dirname "$0"`
-
-if [ $LOCI_DEVEL ]
+if [ -z "$BF_DEVEL" ]
 then
-  java -mx512m $PROG "$@"
-elif [ -e "$DIR/ij.jar" ] && \
-  ([ -e "$DIR/loci_tools.jar" ] || [ -e "$DIR/loci_plugins.jar" ])
-then
-  java -mx512m -cp "$DIR":"$DIR/loci_plugins.jar":"$DIR/loci_tools.jar":"$DIR/ij.jar" $PROG "$@"
-else
-  echo "Required JAR libraries not found. Please download:"
-  echo "  loci_tools.jar"
-  echo "from:"
-  echo "  http://www.loci.wisc.edu/bio-formats/downloads"
-  echo "and:"
-  echo "  ij.jar"
-  echo "from:"
-  echo "  http://rsb.info.nih.gov/ij/upgrade/"
-  echo "and place in the same directory as the command line tools."
+  # Developer environment variable unset; add JAR libraries to classpath.
+  if [ -e "$BF_JAR_DIR/ij.jar" ]
+  then
+    BF_CP="$BF_JAR_DIR/ij.jar"
+  else
+    # Libraries not found; issue an error
+    echo "Required JAR libraries not found. Please download:"
+    echo "  ij.jar"
+    echo "from:"
+    echo "  http://imagej.nih.gov/ij/upgrade/"
+    echo "and place in the same directory as the command line tools."
+    echo ""
+    exit 3
+  fi
+  if [ -e "$BF_JAR_DIR/bio-formats_plugins.jar" ]
+  then
+    BF_CP="$BF_CP:$BF_JAR_DIR/bio-formats_plugins.jar"
+  elif [ ! -e "$BF_JAR_DIR/loci_tools.jar" -a ! -e bioformats_package.jar ]
+  then
+    # Libraries not found; issue an error
+    echo "Required JAR libraries not found. Please download:"
+    echo "  bioformats_package.jar"
+    echo "from:"
+    echo "  http://www.openmicroscopy.org/site/products/bio-formats/downloads"
+    echo "and place in the same directory as the command line tools."
+    echo ""
+    exit 4
+  fi
 fi
+
+BF_PROG=loci.plugins.in.Importer \
+  BF_CP="$BF_CP" "$BF_DIR/bf.sh" "$@"
